//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnrolledAccount
    {
        public int iAccountID { get; set; }
        public string tUsername { get; set; }
        public string tPassword { get; set; }
        public string tFullname { get; set; }
        public string tEmailAddress { get; set; }
        public string tContactNumber { get; set; }
        public string tAccountType { get; set; }
        public decimal iLoadAmount { get; set; }
        public int bSMS { get; set; }
        public System.DateTime dDateRegistered { get; set; }
        public int bActive { get; set; }
    }
}
